name: Release Windows CLI Installer

on:
    workflow_dispatch:
    workflow_call:

env:
    GITHUB_TOKEN: ${{ secrets.ETOKEN }}

permissions:
    contents: write

jobs:
    Upload:
        name: Upload Windows PowerShell Installer
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Upload install-windows.ps1 to release
              run: |
                  gh release upload v1.0.0-stable --clobber installer/install-windows.ps1
