name: Release Windows CLI Installer

on:
    workflow_dispatch:
    workflow_call:

env:
    GH_TOKEN: ${{ github.token }}

permissions:
    contents: write

jobs:
    Upload:
        name: Upload Windows PowerShell Installer
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Upload NunWindowsCLIInstaller.ps1 to release
              run: |
                  gh release upload v1.0.0-stable --clobber installer/NunWindowsCLIInstaller.ps1
