name: Release Linux Installer

on:
    workflow_dispatch:
    workflow_call:

env:
    GITHUB_TOKEN: ${{ github.token }}

permissions:
    contents: write

jobs:
    Upload:
        name: Upload Linux Installer Script
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Upload NunLinuxInstaller.sh to release
              run: |
                  gh release upload v1.0.0-stable --clobber installer/NunLinuxInstaller.sh
